version: "2"

services:
  portus:
    image: opensuse/portus:head
    environment:
      - PORTUS_MACHINE_FQDN_VALUE=${MACHINE_FQDN}

      # DB. The password for the database should definitely not be here. You are
      # probably better off with Docker Swarm secrets.
      - PORTUS_DB_HOST=db
      - PORTUS_DB_DATABASE=portus_production
      - PORTUS_DB_PASSWORD=${DATABASE_PASSWORD}
      - PORTUS_DB_POOL=5

      # Secrets. It can possibly be handled better with Swarm's secrets.
      - PORTUS_SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PORTUS_KEY_PATH=/certificates/portus.key
      - PORTUS_PASSWORD=${PORTUS_PASSWORD}

      # SSL
      - PORTUS_PUMA_TLS_KEY=/certificates/portus.key
      - PORTUS_PUMA_TLS_CERT=/certificates/portus.crt

      # NGinx is serving the assets instead of Puma. If you want to change this,
      # uncomment this line.
      #- RAILS_SERVE_STATIC_FILES='true'

      # LDAP
      - PORTUS_LDAP_ENABLED=true
      - PORTUS_LDAP_HOSTNAME=docker.registry.local
      - PORTUS_LDAP_PORT=389
      - PORTUS_LDAP_UID=uid
      - PORTUS_LDAP_BASE=dc=registry,dc=local
      - PORTUS_LDAP_GROUP_BASE=dc=registry,dc=local
      - PORTUS_LDAP_FILTER=
      - PORTUS_LDAP_AUTHENTICATION_ENABLED=true
      - PORTUS_LDAP_AUTHENTICATION_BIND_DN=cn=admin,dc=registry,dc=local
      - PORTUS_LDAP_AUTHENTICATION_PASSWORD=JonSn0w
      - PORTUS_LDAP_ENCRYPTION_METHOD=start_tls
      - PORTUS_LDAP_ENCRYPTION_OPTIONS_CA_FILE=/ldap-certificates/ca.pem
      - PORTUS_LDAP_ENCRYPTION_OPTIONS_SSL_VERSION=TLSv1_2
    ports:
      - 29300:3000
    links:
      - db
    volumes:
      - ./secrets:/certificates:ro
      - ./secrets/ldap:/ldap-certificates:ro
      - static:/srv/Portus/public
      - /etc/hosts:/etc/hosts:ro

  background:
    image: opensuse/portus:head
    depends_on:
      - portus
      - db
    environment:
      # Theoretically not needed, but cconfig's been buggy on this...
      - CCONFIG_PREFIX=PORTUS
      - PORTUS_MACHINE_FQDN_VALUE=${MACHINE_FQDN}

      # DB. The password for the database should definitely not be here. You are
      # probably better off with Docker Swarm secrets.
      - PORTUS_DB_HOST=db
      - PORTUS_DB_DATABASE=portus_production
      - PORTUS_DB_PASSWORD=${DATABASE_PASSWORD}
      - PORTUS_DB_POOL=5

      # Secrets. It can possibly be handled better with Swarm's secrets.
      - PORTUS_SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PORTUS_KEY_PATH=/certificates/portus.key
      - PORTUS_PASSWORD=${PORTUS_PASSWORD}

      # LDAP
      - PORTUS_LDAP_ENABLED=true
      - PORTUS_LDAP_HOSTNAME=docker.registry.local
      - PORTUS_LDAP_PORT=389
      - PORTUS_LDAP_UID=uid
      - PORTUS_LDAP_BASE=dc=registry,dc=local
      - PORTUS_LDAP_GROUP_BASE=ou=canigo,dc=registry,dc=local
      - PORTUS_LDAP_FILTER=
      - PORTUS_LDAP_AUTHENTICATION_ENABLED=true
      - PORTUS_LDAP_AUTHENTICATION_BIND_DN=cn=admin,dc=registry,dc=local
      - PORTUS_LDAP_AUTHENTICATION_PASSWORD=JonSn0w
      - PORTUS_LDAP_ENCRYPTION_METHOD=start_tls
      - PORTUS_LDAP_ENCRYPTION_OPTIONS_CA_FILE=/ldap-certificates/ca.pem
      - PORTUS_LDAP_ENCRYPTION_OPTIONS_SSL_VERSION=TLSv1_2

      - PORTUS_BACKGROUND=true
    links:
      - db
    volumes:
      - ./secrets:/certificates:ro
      - ./secrets/ldap:/ldap-certificates:ro
      - /etc/hosts:/etc/hosts:ro

  db:
    image: library/mariadb:10.0.23
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    environment:
      - MYSQL_DATABASE=portus_production

      # Again, the password shouldn't be handled like this.
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - /var/lib/portus/mariadb:/var/lib/mysql

  registry:
    image: library/registry:2.6
    command: ["/bin/sh", "/etc/docker/registry/init"]
    environment:
      # Authentication
      REGISTRY_AUTH_TOKEN_REALM: https://${MACHINE_FQDN}/v2/token
      REGISTRY_AUTH_TOKEN_SERVICE: ${MACHINE_FQDN}
      REGISTRY_AUTH_TOKEN_ISSUER: ${MACHINE_FQDN}
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /secrets/portus.crt

      # SSL
      REGISTRY_HTTP_TLS_CERTIFICATE: /secrets/portus.crt
      REGISTRY_HTTP_TLS_KEY: /secrets/portus.key

      # Portus endpoint
      REGISTRY_NOTIFICATIONS_ENDPOINTS: >
        - name: portus
          url: https://${MACHINE_FQDN}/v2/webhooks/events
          timeout: 2000ms
          threshold: 5
          backoff: 1s
    volumes:
      - /var/lib/portus/registry:/var/lib/registry
      - ./secrets:/secrets:ro
      - ./registry/config.yml:/etc/docker/registry/config.yml:ro
      - ./registry/init:/etc/docker/registry/init:ro
      - /etc/hosts:/etc/hosts:ro
    ports:
      - 29500:5000
      - 29501:5001 # required to access debug service
    links:
      - portus:portus

  ldap:
    image: osixia/openldap:1.5.0
    command: --loglevel debug
    restart: always
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_ORGANISATION=SOHO
      - LDAP_DOMAIN=registry.local
      - LDAP_ADMIN_PASSWORD=JonSn0w
      - LDAP_TLS_ENFORCE=true
      - LDAP_TLS_CRT_FILENAME=ldap.crt
      - LDAP_TLS_KEY_FILENAME=ldap.key
      - LDAP_TLS_CA_CRT_FILENAME=ca.crt
      - LDAP_TLS_VERIFY_CLIENT=never
    volumes:
      - "/srv/openldap/slapd/database:/var/lib/ldap"
      - "/srv/openldap/slapd/config:/etc/ldap/slapd.d"
      - "/srv/openldap/slapd/ldifs:/container/service/slapd/assets/custome"
      - "/srv/openldap/slapd/secrets/certs:/container/service/slapd/assets/certs"

  nginx:
    image: library/nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./secrets:/secrets:ro
      - static:/srv/Portus/public:ro
    ports:
      - 29080:80
      - 29443:443
    links:
      - registry:registry
      - portus:portus

volumes:
  static:
    driver: local
